blog/urls.py
from django.urls import __path__
from . import views
from django.urls import path

app_name='blog'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.reader,name='reader'),
    path('postnew',views.postnew,name='postnew'),
    path('submit',views.submit,name='submit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
]

polls/urls.py
from django.urls import __path__
from . import views
from django.urls import path


app_name='polls'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results/',views.Resultsview.as_view(),name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote')
]

blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib import admin
import datetime
# Create your models here.
class BlogPost(models.Model):
    def __str__(self):
        return self.blog_post
    blog_post = models.TextField('Blog post',max_length=200)
    publisher_name = models.CharField('Publisher name',max_length=200)
    blog_subject = models.CharField('Blog subject',max_length=100)
    
    pub_date = models.DateTimeField('date published')
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
import datetime
# Create your models here.
class Question(models.Model):
    def __str__(self):
        return self.question_text
    question_text = models.CharField('Vraag teks',max_length=200)
    pub_date = models.DateTimeField('date published')
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        

class Choice(models.Model):
    def __str__(self):
        return self.choice_text    
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('die teks vir die keuse',max_length=200)
    votes = models.IntegerField('telling',default=0)

testingnewapp/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from .models import BlogPost
from django.urls import reverse
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_blog_list'

    def get_queryset(self):
        """Return the last five blog posts."""

        return BlogPost.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:510]
 
def reader(request,pk):
    blog_post = get_object_or_404(BlogPost,pk=pk)
    template_name='blog/reader.html'
    print("running code at ",pk,blog_post.blog_subject)
    #blog_post_subject = blog_post.blog_subject
    return render (request,template_name,{'blog_post_subject':blog_post.blog_subject,id:pk,'blog_post':blog_post,'blog_post_content':blog_post.blog_post})


def postnew(request):
    print("this is rendering")
    return render(request,'blog/postnew.html')
    #return HttpResponseRedirect(reverse('blog:index'))

def submit(request):
    print("running this code - fritz")
    blog_post = BlogPost()
    blog_post.publisher_name=request.POST['fname']
    blog_post.blog_subject=request.POST['lname']
    blog_post.blog_post=request.POST['blog']
    blog_post.pub_date = timezone.now()
    if len(blog_post.blog_subject) < 3:
        return render (request,'blog/postnew.html', {'error_message': "Subject was too short, post not accepted"})
    else:
        print('subject and subject length:',len(blog_post.blog_subject),blog_post.blog_subject)
    blog_post.save()
    return HttpResponseRedirect(reverse('blog:index'))

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from .models import Question,Choice
from django.urls import reverse
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""

        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class Resultsview(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    #return HttpResponse("You're voting on question %s." %question_id)
    question = get_object_or_404(Question,pk=question_id)
    print("page loaded increased")
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        print("choice selecte")
    except (KeyError, Choice.DoesNotExist):
        print("choice selected NOT")
        return render (request,'polls/detail.html', {'question':question, 'error_message': "You didn't select a choice."})
    else:
        print("Vote increased on the second place")
        selected_choice.votes += 1
        selected_choice.save()
        print('reversed result:',reverse('polls:results', args=(question.id,)))
        #return HttpResponseRedirect('../../'+str(question.id)+"/results")

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

testingnewapp/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/index.css' %}">
<html>
{% if latest_blog_list %}
<h1>Recent blogs</h1>
<ul>
{% for blog in latest_blog_list %}
<li><a  href="{% url 'blog:reader' blog.id %}"> {{ blog.blog_subject }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No blogs are available</p>
{% endif %}

<a href="{% url 'blog:postnew' %}">post new</a>
</html>

blog/templates/blog/postnew.html
<form action="{% url 'blog:submit'  %}" method="post">
{% csrf_token %}

<fieldset>

        <h1>Post new blog</h1>
    {% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}    

        <label for="fname">Publisher name</label><br>
        <input type="text" id="fname" name="fname"><br>
        <label for="lname">Subject</label><br>
        <input type="text" id="lname" name="lname"><br>
        <label for="bname">Blog</label><br>
        <input type="text" id="blog" name="blog">
        

</fieldset>
<input type="submit" value="Submit">
</form>

blog/templates/blog/reader.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/reader.css' %}">
<h1> {{ blog_post_subject }}</h1>
        
<p>{{ blog_post_content }} test</p>

<a href="../">Return to index view</a>

blog/templates/blog/results.html
<h1>{{ question.question_text }}</h1>

<ul>

    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}

</ul>
<a href="{% url 'polls:detail' question.id %}"> Vote again?</a>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}

<fieldset>

    <legend>
        <h1>{{ question.question_text }}</h1>
    </legend>
    {% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}    

    {% for choice in question.choice_set.all %}
<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
<label for="choice{{ forloop.counter }}"> {{ choice.choice_text }} </label><br>
{% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<html>
{% if latest_question_list %}

<ul>
{% for question in latest_question_list %}
<li><a href="{% url 'polls:detail' question.id %}"> {{ question.question_text }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No polls are available</p>
{% endif %}
<p>fritz was here2</p>
</html>